# Rendimento Turista per Sempre
Download and cleaning dei rendimenti del gratta e vinci Turista per Sempre per analisi [Misure di Rischio](./misure_rischio.ipynb).

In [1]:
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
import datetime
sns.set_style("whitegrid")
# sns.set_theme()
matplotlib.rcParams['figure.figsize'] = [9.0/2, 5.0/2]

In [2]:
qt_tot = 54720000
df = pd.read_html("https://www.adm.gov.it/portale/-/new-turista-per-sempre",
    decimal=',', thousands='.')
df = df[0]
df

,Importo premi,N. biglietti vincenti per blocco iniziale di biglietti (N. 54.720.000),Probabilità di vincita 1 biglietto vincente ogni
0,1936849.00,12,4560000.00
1,50000.00,24,2280000.00
2,10000.00,96,570000.00
3,5000.00,204,268235.29
4,1000.00,3648,15000.00
5,500.00,3192,17142.86
6,200.00,58140,941.18
7,100.00,129960,421.05
8,50.00,394440,138.73
9,20.00,912000,60.00
10,15.00,1185600,46.15
11,10.00,5016000,10.91
12,5.00,7296000,"esclusa ai sensi dell’art. 9, comma 1-ter del ..."
13,Totali,14.999.316 biglietti vincenti su 54.720.000 bi...,"1 biglietto ogni 7,10 è vincente premi superio..."

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 3 columns):
 #   Column                                                                  Non-Null Count  Dtype
---  ------                                                                  --------------  -----
 0   Importo premi                                                           14 non-null     object
 1   N. biglietti vincenti per blocco iniziale di biglietti (N. 54.720.000)  14 non-null     object
 2   Probabilità di vincita 1 biglietto vincente ogni                        14 non-null     object
dtypes: object(3)
memory usage: 468.0+ bytes

In [4]:
df_clean = df.rename(columns={
    df.columns[0]: "vincita",
    df.columns[1]: "qt",
    df.columns[2]: "1_qt"})
df_clean.vincita = pd.to_numeric(df_clean.vincita, errors="coerce")
df_clean.qt = pd.to_numeric(df_clean.qt, errors="coerce")
df_clean["1_qt"] = pd.to_numeric(df_clean["1_qt"], errors="coerce")

# df_clean = df_clean.drop(13)
# df_clean = pd.concat([df_clean, pd.DataFrame([0])], axis=0, ignore_index=True)
df_clean.loc[13, "vincita"] = 0
df_clean.loc[13, "qt"] = qt_tot - df_clean.loc[0:12, "qt"].sum()
df_clean["1_qt"] =  qt_tot / df_clean.qt
df_clean["prob"] = 1 / df_clean["1_qt"]
df_clean["prob cum"] = df_clean.prob.cumsum()
df_clean

      vincita          qt          1_qt          prob      prob cum
0   1936849.0        12.0  4.560000e+06  2.192982e-07  2.192982e-07
1     50000.0        24.0  2.280000e+06  4.385965e-07  6.578947e-07
2     10000.0        96.0  5.700000e+05  1.754386e-06  2.412281e-06
3      5000.0       204.0  2.682353e+05  3.728070e-06  6.140351e-06
4      1000.0      3648.0  1.500000e+04  6.666667e-05  7.280702e-05
5       500.0      3192.0  1.714286e+04  5.833333e-05  1.311404e-04
6       200.0     58140.0  9.411765e+02  1.062500e-03  1.193640e-03
7       100.0    129960.0  4.210526e+02  2.375000e-03  3.568640e-03
8        50.0    394440.0  1.387283e+02  7.208333e-03  1.077697e-02
9        20.0    912000.0  6.000000e+01  1.666667e-02  2.744364e-02
10       15.0   1185600.0  4.615385e+01  2.166667e-02  4.911031e-02
11       10.0   5016000.0  1.090909e+01  9.166667e-02  1.407770e-01
12        5.0   7296000.0  7.500000e+00  1.333333e-01  2.741103e-01
13        0.0  39720684.0  1.377620e+00  7.258897e-01  1.000000e+00

In [7]:
%pwd

'/home/andrea/Documents/analisi_investimenti'

In [8]:
df_clean.to_csv("dati/turista_per_sempre.csv", index=False)